import mongoose from "mongoose"

const userSchema = new mongoose.Schema(
    {
        profileId: {
            type: String,
        },
        bio: {
            type: String,
            default: "Autogenerated bio",
        },
    },
    { timestamps: true }
)

let Users = mongoose.model.users || mongoose.model("users", userSchema)

export default Users
